### PR TITLE
Nicer Ids

### LINKED ISSUE #32: Nice IDS
might use the same ones as station api unless they aren't cursed enough

### PR DESCRIPTION
**Pull request by valoeghese**
Also has datafixers for old ids

Fixes #32

### CODE REVIEW

**Comment by valoeghese** [comment]
Reviews pls

**Review by CoolMineman — APPROVED** [review]
looks fine

**Review by williambl — COMMENTED** [review]
Are these entirely based on translation keys or are they diverging from that to create a nicer id in some places?

If they're diverging, will the inconsistency of some ids having underscores and some having none be resolved? (e.g. `deadbush` vs `brown_mushroom`)

**Comment by valoeghese** [comment]
They're based off of the names we gave them in plasma mappings, which, in turn, were based off of translation keys.

**Comment by valoeghese** [comment]
and in regards to the deadbush thing, it's no worse than mojang. The id of dead bushes was `minecraft:deadbush` until 1.13

**Comment by williambl** [comment]
Sure, but we can be better than Mojang. That said, I suppose it's best to have inconsistencies if it's necessary to have full consistency with what people in the b1.7.3 community call these blocks.

**Comment by valoeghese** [comment]
You're talking to me, who left repeaters as minecraft:diode, saying "we can be better than mojang"

**Comment by valoeghese** [comment]
Want me to change deadbushes then?

**Comment by williambl** [comment]
It's up to you really - personally I would use material-prefixed underscored names (`dead_bush`, `cloth_helmet`), but that's just my style. I'd be fine with anything as long as the names aren't too surprising.

**Comment by valoeghese** [comment]
actually we kept repeaters as redstone_repeater... :thinking:

**Comment by valoeghese** [comment]
perhaps I'm thinking of older plasma versions

**Comment by valoeghese** [comment]
I changed some ids. I'm waiting on 2 approvals from organisation members before merging

**Comment by valoeghese** [comment]
Reviews pls

**Review by williambl — APPROVED** [review]

**Pull request merged**
